server:
  port: 9001

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cloud-user-consumer-openfeign
          uri: lb://cloud-user-consumer-openfeign
          predicates:
            - Path=/user/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka01:8001/eureka/,http://eureka02:8002/eureka/,http://eureka03:8003/eureka/
# 配置Gateway日志等级，输出转发细节信息
logging:
  level:
    org.springframework.cloud.gateway: debug
