#服务端口号
server:
  port: 8002
  servlet:
    context-path: /
#服务名称
spring:
  application:
    name: eureka-service
#eureka 配置
eureka:
  instance:
    hostname: eureka02
  client:
    #server自身不注册入eureka
    register-with-eureka: false
    fetch-registry: false
    #注册地址
    serviceUrl:
      defaultZone: http://eureka01:8001/eureka/,http://eureka03:8003/eureka/
